{{ if eq .Values.env "prod" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
    nginx.ingress.kubernetes.io/configuration-snippet: |

      # blacklist
      deny 86.110.188.78/32;
      deny 185.71.65.169/32;
      deny 176.8.34.42/32;
      deny 46.35.245.1/32;
      deny 193.26.217.232/32;
      deny 198.11.128.0/18;
      deny 42.120.0.0/16;
      deny 106.11.0.0/16;
      deny 78.140.132.121/32;
      deny 213.196.45.116/32;
      deny 31.31.196.111/32;
      allow all;
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}

{{ else }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
    nginx.ingress.kubernetes.io/configuration-snippet: |

      real_ip_header CF-Connecting-IP;
      set_real_ip_from 10.0.0.0/8;

      # Ivan Admin IP
      allow 37.77.108.7;
      allow 85.249.160.105;
      allow 37.146.241.10;
      allow 37.146.245.55;
      allow 37.146.245.48;

      # Service IP
      allow 35.198.180.223;
      allow 2001:67c:11d4:6387::0/64;
      allow 2001:67c:11d4:6f44::0/64;
      allow 2001:67c:11d4:5c28::0/64;
      allow 2001:67c:11d4:68b6::0/64;
      allow 2001:67c:11d4:4733::0/64;
      allow 2001:67c:11d4:45a8::0/64;
      allow 2001:67c:11d4:7c17::0/64;

      # Service IP
      allow 35.204.228.227;
      allow 35.204.28.253;

      # Internal networks
      allow 127.0.0.1/32;
      allow 192.168.0.0/16;
      allow 172.16.0.0/12;
      allow 10.0.0.0/8;

      # evoplay
      allow 213.160.135.182/32;   # CF Office
      allow 46.164.141.90/32;     # CF Office
      allow 149.255.128.6/32;     # CF Office
      allow 91.197.186.57/32;     # CF Office
      allow 23.109.21.28/32;      # CF VPN
      allow 23.109.21.148/32;     # CF VPN
      allow 23.109.21.108/32;     # CF VPN
      allow 5.45.79.29/32;        # CF VPN
      allow 23.109.22.52/32;      # CF VPN
      allow 23.109.22.44/32;      # CF VPN
      allow 178.128.251.197/32;   # CF VPN
      allow 37.1.218.18/32;       # CF VPN
      allow 37.1.207.113/32;      # CF VPN
      allow 5.45.79.30/32;        # CF VPN
      allow 65.21.131.109/32;     # VPN
      deny all;

  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}

{{ end }}

spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name }}
              port:
                number: 80
