apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
{{- end }}